name: Terraform Plan

on:
  pull_request:
    branches:
      - main  # Chạy khi có PR vào main

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: mock-project #ubuntu-latest #GitHub hosted - Sharing between

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
            aws-region: ap-southeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan
