name: Terraform Plan

on:
  pull_request:
    branches:
      - main  # Chạy khi có PR vào main

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: mock-project #ubuntu-latest #GitHub hosted - Sharing between

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies  # Cài đặt unzip & Node.js
        run: |
          sudo apt-get update 
          sudo apt-get install -y unzip nodejs

      - name: Install AWS CLI  # Thêm bước cài đặt AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          aws --version  # Kiểm tra phiên bản AWS CLI

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
            aws-region: ap-southeast-1

      - name: Download terraform.tfvars from S3
        run: |
          aws s3 cp s3://luan-mock-project/terraform.tfvars terraform.tfvars

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./CICD-modules/environments/dev

      - name: Terraform Plan
        run: terraform plan -var-file=terraform.tfvars -out=tfplan
        working-directory: ./CICD-modules/environments/dev
